version: '3.7'
services:
  mongo:
    image: mongo:4.2.3-bionic
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017